spring:
  application:
    name: 'naming-service'
#  cloud:
#    config:
#      enabled: false
  config:
    import:
      - optional:configserver:http://localhost:8888/
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false